# Generated by Django 5.2.5 on 2025-08-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='location',
            field=models.CharField(default='Main Office', help_text='Where the car is located', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='seats',
            field=models.IntegerField(default=4, help_text='Number of seats in the car'),
            preserve_default=False,
        ),
    ]
